name: build workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    jobs:
      build:
      runs-on: ubuntu-latest
      steps:
       -name code checkout
        uses: actions/checkout@v2

        -name:run tests on the main branch
        run: mvn test

        -name:checksytle
        run: mvn checkstyle:check