name: build workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: run tests on the main branch
        run: mvn test

      - name: checkstyle
        run: mvn checkstyle:check